### assumes ubuntu image
---
- name: update apt cache
  apt: update_cache=yes
  become: true

- name: install packages
  apt: 
      pkg: 
          - curl
          - build-essential
          - git
          - pkg-config
      state: latest
  become: true

- name: create directory
  file:
    path: {{ home }}/genome_tools
    state: directory
    mode: 0775

- name: install nextflow
  include_tasks: nextflow.yml

- name: install singularity
  include_tasks: singularity.yml

- name: install docker
  include_tasks: docker.yml
