name: ansible-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          options: |
            --verbose

      - name: test VG_1
        run: |
          cd VG_1
          mkdir input_tool1
          wget -O input_tool1/test2.fa https://www.ebi.ac.uk/ena/browser/api/fasta/GCA_002849515.1
          nextflow run tool_1.nf
